// <auto-generated />
using System;
using ECOCEMProyect.migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECOCEMProyect.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20231115153227_InicialCreate")]
    partial class InicialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccionMantenimientoOrdenTrabajo", b =>
                {
                    b.Property<int>("AccionesMantenimientoAMId")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenesTrabajoEquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenesTrabajoBrigadaId")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenesTrabajoTrabajadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrdenesTrabajoFechaId")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccionesMantenimientoAMId", "OrdenesTrabajoEquipoId", "OrdenesTrabajoBrigadaId", "OrdenesTrabajoTrabajadorId", "OrdenesTrabajoFechaId");

                    b.HasIndex("OrdenesTrabajoEquipoId", "OrdenesTrabajoBrigadaId", "OrdenesTrabajoTrabajadorId", "OrdenesTrabajoFechaId");

                    b.ToTable("AccionMantenimientoOrdenTrabajo");
                });

            modelBuilder.Entity("ECOCEMProyect.AccionMantenimiento", b =>
                {
                    b.Property<int>("AMId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AMId"));

                    b.Property<int>("BrigadaId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.HasKey("AMId");

                    b.ToTable("AccionesMantenimientos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AccionMantenimiento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ECOCEMProyect.Bascula", b =>
                {
                    b.Property<int>("BasculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BasculaId"));

                    b.HasKey("BasculaId");

                    b.ToTable("Basculas");
                });

            modelBuilder.Entity("ECOCEMProyect.Brigada", b =>
                {
                    b.Property<int>("BrigadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrigadaId"));

                    b.HasKey("BrigadaId");

                    b.ToTable("Brigadas");
                });

            modelBuilder.Entity("ECOCEMProyect.Carga", b =>
                {
                    b.Property<int>("TipoCementoId")
                        .HasColumnType("integer");

                    b.Property<int>("SiloId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCargaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntidadCompradoraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVentaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<int>("VentaEntidadCompradoraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VentaFechaVentaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VentaSedeId")
                        .HasColumnType("integer");

                    b.HasKey("TipoCementoId", "SiloId", "VehiculoId", "FechaCargaId");

                    b.HasIndex("VentaSedeId", "VentaEntidadCompradoraId", "VentaFechaVentaId");

                    b.ToTable("Cargas");
                });

            modelBuilder.Entity("ECOCEMProyect.Compra", b =>
                {
                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<int>("FabricaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaId")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SedeId", "FabricaId", "FechaId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("ECOCEMProyect.Descarga", b =>
                {
                    b.Property<int>("TipoCementoId")
                        .HasColumnType("integer");

                    b.Property<int>("SiloId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("compraFabricaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("compraFechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("compraSedeId")
                        .HasColumnType("integer");

                    b.HasKey("TipoCementoId", "SiloId", "VehiculoId", "FechaId");

                    b.HasIndex("compraSedeId", "compraFabricaId", "compraFechaId");

                    b.ToTable("Descargas");
                });

            modelBuilder.Entity("ECOCEMProyect.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmpresaId"));

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("ECOCEMProyect.EntidadCompradora", b =>
                {
                    b.Property<int>("EntidadCompradoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntidadCompradoraId"));

                    b.HasKey("EntidadCompradoraId");

                    b.ToTable("EntidadCompradoras");
                });

            modelBuilder.Entity("ECOCEMProyect.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EquipoId"));

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEId")
                        .HasColumnType("integer");

                    b.HasKey("EquipoId");

                    b.HasIndex("SedeId");

                    b.HasIndex("TipoEId")
                        .IsUnique();

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ECOCEMProyect.Fabrica", b =>
                {
                    b.Property<int>("FabricaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FabricaId"));

                    b.HasKey("FabricaId");

                    b.ToTable("Fabricas");
                });

            modelBuilder.Entity("ECOCEMProyect.HerramientaMantNecesario", b =>
                {
                    b.Property<int>("HerramientasId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("AMId")
                        .HasColumnType("integer");

                    b.Property<double>("HorasExpId")
                        .HasColumnType("double precision");

                    b.Property<int>("CantidadR")
                        .HasColumnType("integer");

                    b.Property<int?>("MantenimientoNecesarioAMId")
                        .HasColumnType("integer");

                    b.Property<double?>("MantenimientoNecesarioHorasExpId")
                        .HasColumnType("double precision");

                    b.Property<int?>("MantenimientoNecesarioTipoEquipoId")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedidaR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HerramientasId", "TipoEquipoId", "AMId", "HorasExpId");

                    b.HasIndex("MantenimientoNecesarioTipoEquipoId", "MantenimientoNecesarioAMId", "MantenimientoNecesarioHorasExpId");

                    b.ToTable("HerramientaMantNecesario");
                });

            modelBuilder.Entity("ECOCEMProyect.Herramientas", b =>
                {
                    b.Property<int>("HerramientasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HerramientasId"));

                    b.HasKey("HerramientasId");

                    b.ToTable("Herramientas");
                });

            modelBuilder.Entity("ECOCEMProyect.MantenimientoNecesario", b =>
                {
                    b.Property<int>("TipoEquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("AMId")
                        .HasColumnType("integer");

                    b.Property<double>("HorasExpId")
                        .HasColumnType("double precision");

                    b.HasKey("TipoEquipoId", "AMId", "HorasExpId");

                    b.HasIndex("AMId");

                    b.ToTable("MantenimientosNecesarios");
                });

            modelBuilder.Entity("ECOCEMProyect.MedicionBascula", b =>
                {
                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.Property<int>("BasculaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaBId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CargaFechaCargaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CargaSiloId")
                        .HasColumnType("integer");

                    b.Property<int?>("CargaTipoCementoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CargaVehiculoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DescargaFechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DescargaSiloId")
                        .HasColumnType("integer");

                    b.Property<int?>("DescargaTipoCementoId")
                        .HasColumnType("integer");

                    b.Property<int?>("DescargaVehiculoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCargaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PesoB")
                        .HasColumnType("integer");

                    b.Property<int>("SiloId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCementoId")
                        .HasColumnType("integer");

                    b.HasKey("VehiculoId", "BasculaId", "FechaBId");

                    b.HasIndex("CargaTipoCementoId", "CargaSiloId", "CargaVehiculoId", "CargaFechaCargaId");

                    b.HasIndex("DescargaTipoCementoId", "DescargaSiloId", "DescargaVehiculoId", "DescargaFechaId");

                    b.ToTable("MedicionesBasculas");
                });

            modelBuilder.Entity("ECOCEMProyect.MedicionSilo", b =>
                {
                    b.Property<int>("SiloId")
                        .HasColumnType("integer");

                    b.Property<int>("MedidorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaMId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CargaFechaCargaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CargaSiloId")
                        .HasColumnType("integer");

                    b.Property<int?>("CargaTipoCementoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CargaVehiculoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DescargaFechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DescargaSiloId")
                        .HasColumnType("integer");

                    b.Property<int?>("DescargaTipoCementoId")
                        .HasColumnType("integer");

                    b.Property<int?>("DescargaVehiculoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCargaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<int>("PesoM")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCementoId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.Property<int>("Volumen")
                        .HasColumnType("integer");

                    b.HasKey("SiloId", "MedidorId", "FechaMId");

                    b.HasIndex("CargaTipoCementoId", "CargaSiloId", "CargaVehiculoId", "CargaFechaCargaId");

                    b.HasIndex("DescargaTipoCementoId", "DescargaSiloId", "DescargaVehiculoId", "DescargaFechaId");

                    b.ToTable("MedicionesSilos");
                });

            modelBuilder.Entity("ECOCEMProyect.Medidor", b =>
                {
                    b.Property<int>("MedidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MedidorId"));

                    b.HasKey("MedidorId");

                    b.ToTable("Medidores");
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajo", b =>
                {
                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("BrigadaId")
                        .HasColumnType("integer");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaId")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EquipoId", "BrigadaId", "TrabajadorId", "FechaId");

                    b.HasIndex("BrigadaId");

                    b.ToTable("OrdenTrabajo");
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajoAMRealizada", b =>
                {
                    b.Property<int>("AMId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("BrigadaId")
                        .HasColumnType("integer");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AMId", "EquipoId", "BrigadaId", "TrabajadorId", "FechaId");

                    b.HasIndex("EquipoId", "BrigadaId", "TrabajadorId", "FechaId");

                    b.ToTable("OrdenTrabajoAMRealizada");
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajoAtendida", b =>
                {
                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DiaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BrigadaId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("NoHoras")
                        .HasColumnType("double precision");

                    b.Property<int?>("OrdenTrabajoBrigadaId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrdenTrabajoEquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OrdenTrabajoFechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OrdenTrabajoTrabajadorId")
                        .HasColumnType("integer");

                    b.Property<double>("PrecioPorHora")
                        .HasColumnType("double precision");

                    b.HasKey("TrabajadorId", "DiaId");

                    b.HasIndex("OrdenTrabajoEquipoId", "OrdenTrabajoBrigadaId", "OrdenTrabajoTrabajadorId", "OrdenTrabajoFechaId");

                    b.ToTable("OrdenesTrabajoAtendidas");
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajoHerramienta", b =>
                {
                    b.Property<int>("HerramientasId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("BrigadaId")
                        .HasColumnType("integer");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CantidadU")
                        .HasColumnType("integer");

                    b.Property<double>("Precio")
                        .HasColumnType("double precision");

                    b.Property<string>("UnidadMedidaU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValeAlmacen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HerramientasId", "EquipoId", "BrigadaId", "TrabajadorId", "FechaId");

                    b.HasIndex("EquipoId", "BrigadaId", "TrabajadorId", "FechaId");

                    b.ToTable("OrdenTrabajoHerramienta");
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajoRoturaEquipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("BrigadaId")
                        .HasColumnType("integer");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrdenTrabajoBrigadaId")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenTrabajoEquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrdenTrabajoFechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrdenTrabajoTrabajadorId")
                        .HasColumnType("integer");

                    b.Property<int>("RoturaEquipoEquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RoturaEquipoFechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoturaEquipoRoturaId")
                        .HasColumnType("integer");

                    b.Property<int>("RoturaId")
                        .HasColumnType("integer");

                    b.HasKey("EquipoId", "BrigadaId", "TrabajadorId", "FechaId");

                    b.HasIndex("RoturaEquipoEquipoId", "RoturaEquipoRoturaId", "RoturaEquipoFechaId");

                    b.HasIndex("OrdenTrabajoEquipoId", "OrdenTrabajoBrigadaId", "OrdenTrabajoTrabajadorId", "OrdenTrabajoFechaId");

                    b.ToTable("OrdenTrabajoRoturaEquipo");
                });

            modelBuilder.Entity("ECOCEMProyect.Rotura", b =>
                {
                    b.Property<int>("RoturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoturaId"));

                    b.HasKey("RoturaId");

                    b.ToTable("Roturas");
                });

            modelBuilder.Entity("ECOCEMProyect.RoturaEquipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<int>("RoturaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaId")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EquipoId", "RoturaId", "FechaId");

                    b.ToTable("RoturaEquipo");
                });

            modelBuilder.Entity("ECOCEMProyect.Sede", b =>
                {
                    b.Property<int>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SedeId"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreSede")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UbicacionSede")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SedeId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("ECOCEMProyect.Silo", b =>
                {
                    b.Property<int>("SiloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SiloId"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.HasKey("SiloId");

                    b.HasIndex("EquipoId");

                    b.ToTable("Silos");
                });

            modelBuilder.Entity("ECOCEMProyect.TipoCemento", b =>
                {
                    b.Property<int>("TipoCementoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoCementoId"));

                    b.HasKey("TipoCementoId");

                    b.ToTable("TipoCementos");
                });

            modelBuilder.Entity("ECOCEMProyect.TipoEquipo", b =>
                {
                    b.Property<int>("TipoEId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoEId"));

                    b.Property<string>("TipoE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoEId");

                    b.ToTable("TiposEquipos");
                });

            modelBuilder.Entity("ECOCEMProyect.Trabajador", b =>
                {
                    b.Property<int>("TrabajadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrabajadorId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreTrabajador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.HasKey("TrabajadorId");

                    b.HasIndex("SedeId");

                    b.ToTable("Trabajadores");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Trabajador");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ECOCEMProyect.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculoId"));

                    b.HasKey("VehiculoId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("ECOCEMProyect.Venta", b =>
                {
                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<int>("EntidadCompradoraId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVentaId")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SedeId", "EntidadCompradoraId", "FechaVentaId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Reporte", b =>
                {
                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaId")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CostoMantContratado")
                        .HasColumnType("double precision");

                    b.Property<double>("CostoMantContratadoTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("CostoTotalMant")
                        .HasColumnType("double precision");

                    b.Property<double>("CostoTotalMantFact")
                        .HasColumnType("double precision");

                    b.Property<double>("DisponibilidadReal")
                        .HasColumnType("double precision");

                    b.Property<double>("DisponibilidadRequerida")
                        .HasColumnType("double precision");

                    b.Property<double>("Facturacion")
                        .HasColumnType("double precision");

                    b.Property<double>("IndiceParoFalla")
                        .HasColumnType("double precision");

                    b.Property<double>("IndiceRotura")
                        .HasColumnType("double precision");

                    b.Property<double>("PerdidaIndisponibilidad")
                        .HasColumnType("double precision");

                    b.Property<double>("TiempoOPeracionReal")
                        .HasColumnType("double precision");

                    b.Property<double>("TiempoOperacionRequerido")
                        .HasColumnType("double precision");

                    b.Property<double>("TiempoParoMant")
                        .HasColumnType("double precision");

                    b.Property<double>("TiempoParoTrabajosPlan")
                        .HasColumnType("double precision");

                    b.Property<double>("TiempoRealMant")
                        .HasColumnType("double precision");

                    b.Property<double>("TiempoRealParoFalla")
                        .HasColumnType("double precision");

                    b.Property<double>("TiempoRequeridoAccProgramadas")
                        .HasColumnType("double precision");

                    b.HasKey("EquipoId", "FechaId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("ECOCEMProyect.MantenimientoPlanificado", b =>
                {
                    b.HasBaseType("ECOCEMProyect.AccionMantenimiento");

                    b.HasDiscriminator().HasValue("MantenimientoPlanificado");
                });

            modelBuilder.Entity("ECOCEMProyect.JefeMantenimiento", b =>
                {
                    b.HasBaseType("ECOCEMProyect.Trabajador");

                    b.HasDiscriminator().HasValue("JefeMantenimiento");
                });

            modelBuilder.Entity("AccionMantenimientoOrdenTrabajo", b =>
                {
                    b.HasOne("ECOCEMProyect.AccionMantenimiento", null)
                        .WithMany()
                        .HasForeignKey("AccionesMantenimientoAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECOCEMProyect.OrdenTrabajo", null)
                        .WithMany()
                        .HasForeignKey("OrdenesTrabajoEquipoId", "OrdenesTrabajoBrigadaId", "OrdenesTrabajoTrabajadorId", "OrdenesTrabajoFechaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECOCEMProyect.Carga", b =>
                {
                    b.HasOne("ECOCEMProyect.Venta", "Venta")
                        .WithMany("Cargas")
                        .HasForeignKey("VentaSedeId", "VentaEntidadCompradoraId", "VentaFechaVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ECOCEMProyect.Descarga", b =>
                {
                    b.HasOne("ECOCEMProyect.Compra", "compra")
                        .WithMany("Descargas")
                        .HasForeignKey("compraSedeId", "compraFabricaId", "compraFechaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("compra");
                });

            modelBuilder.Entity("ECOCEMProyect.Equipo", b =>
                {
                    b.HasOne("ECOCEMProyect.Sede", "Sede")
                        .WithMany("Equipos")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECOCEMProyect.TipoEquipo", "TipoEquipo")
                        .WithOne("Equipo")
                        .HasForeignKey("ECOCEMProyect.Equipo", "TipoEId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("ECOCEMProyect.HerramientaMantNecesario", b =>
                {
                    b.HasOne("ECOCEMProyect.Herramientas", "Herramienta")
                        .WithMany("HerramientaMantNecesarios")
                        .HasForeignKey("HerramientasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECOCEMProyect.MantenimientoNecesario", "MantenimientoNecesario")
                        .WithMany("HerramientaMantNecesarios")
                        .HasForeignKey("MantenimientoNecesarioTipoEquipoId", "MantenimientoNecesarioAMId", "MantenimientoNecesarioHorasExpId");

                    b.Navigation("Herramienta");

                    b.Navigation("MantenimientoNecesario");
                });

            modelBuilder.Entity("ECOCEMProyect.MantenimientoNecesario", b =>
                {
                    b.HasOne("ECOCEMProyect.MantenimientoPlanificado", null)
                        .WithMany("MantenimientosNecesarios")
                        .HasForeignKey("AMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECOCEMProyect.TipoEquipo", null)
                        .WithMany("MantenimientosNecesarios")
                        .HasForeignKey("TipoEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECOCEMProyect.MedicionBascula", b =>
                {
                    b.HasOne("ECOCEMProyect.Carga", "Carga")
                        .WithMany("MedicionesBascula")
                        .HasForeignKey("CargaTipoCementoId", "CargaSiloId", "CargaVehiculoId", "CargaFechaCargaId");

                    b.HasOne("ECOCEMProyect.Descarga", "Descarga")
                        .WithMany("MedicionesBascula")
                        .HasForeignKey("DescargaTipoCementoId", "DescargaSiloId", "DescargaVehiculoId", "DescargaFechaId");

                    b.Navigation("Carga");

                    b.Navigation("Descarga");
                });

            modelBuilder.Entity("ECOCEMProyect.MedicionSilo", b =>
                {
                    b.HasOne("ECOCEMProyect.Carga", "Carga")
                        .WithMany("MedicionesSilo")
                        .HasForeignKey("CargaTipoCementoId", "CargaSiloId", "CargaVehiculoId", "CargaFechaCargaId");

                    b.HasOne("ECOCEMProyect.Descarga", "Descarga")
                        .WithMany("MedicionesSilo")
                        .HasForeignKey("DescargaTipoCementoId", "DescargaSiloId", "DescargaVehiculoId", "DescargaFechaId");

                    b.Navigation("Carga");

                    b.Navigation("Descarga");
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajo", b =>
                {
                    b.HasOne("ECOCEMProyect.Brigada", null)
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("BrigadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajoAMRealizada", b =>
                {
                    b.HasOne("ECOCEMProyect.AccionMantenimiento", "AccionMantenimiento")
                        .WithMany("OrdenesAMRealizadas")
                        .HasForeignKey("AMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECOCEMProyect.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("OrdenesAMRealizadas")
                        .HasForeignKey("EquipoId", "BrigadaId", "TrabajadorId", "FechaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionMantenimiento");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajoAtendida", b =>
                {
                    b.HasOne("ECOCEMProyect.Trabajador", null)
                        .WithMany("OrdenesTrabajoAtendidas")
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECOCEMProyect.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany()
                        .HasForeignKey("OrdenTrabajoEquipoId", "OrdenTrabajoBrigadaId", "OrdenTrabajoTrabajadorId", "OrdenTrabajoFechaId");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajoHerramienta", b =>
                {
                    b.HasOne("ECOCEMProyect.Herramientas", "Herramientas")
                        .WithMany("OrdenTrabajoHerramientas")
                        .HasForeignKey("HerramientasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECOCEMProyect.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("OrdenTrabajoHerramientas")
                        .HasForeignKey("EquipoId", "BrigadaId", "TrabajadorId", "FechaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herramientas");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajoRoturaEquipo", b =>
                {
                    b.HasOne("ECOCEMProyect.RoturaEquipo", "RoturaEquipo")
                        .WithMany("OrdenTrabajoRoturaEquipo")
                        .HasForeignKey("RoturaEquipoEquipoId", "RoturaEquipoRoturaId", "RoturaEquipoFechaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECOCEMProyect.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("OrdenTrabajoRoturaEquipo")
                        .HasForeignKey("OrdenTrabajoEquipoId", "OrdenTrabajoBrigadaId", "OrdenTrabajoTrabajadorId", "OrdenTrabajoFechaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("RoturaEquipo");
                });

            modelBuilder.Entity("ECOCEMProyect.Sede", b =>
                {
                    b.HasOne("ECOCEMProyect.Empresa", "Empresa")
                        .WithMany("Sedes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("ECOCEMProyect.Silo", b =>
                {
                    b.HasOne("ECOCEMProyect.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ECOCEMProyect.Trabajador", b =>
                {
                    b.HasOne("ECOCEMProyect.Sede", "Sede")
                        .WithMany("Trabajadores")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("ECOCEMProyect.AccionMantenimiento", b =>
                {
                    b.Navigation("OrdenesAMRealizadas");
                });

            modelBuilder.Entity("ECOCEMProyect.Brigada", b =>
                {
                    b.Navigation("OrdenesTrabajo");
                });

            modelBuilder.Entity("ECOCEMProyect.Carga", b =>
                {
                    b.Navigation("MedicionesBascula");

                    b.Navigation("MedicionesSilo");
                });

            modelBuilder.Entity("ECOCEMProyect.Compra", b =>
                {
                    b.Navigation("Descargas");
                });

            modelBuilder.Entity("ECOCEMProyect.Descarga", b =>
                {
                    b.Navigation("MedicionesBascula");

                    b.Navigation("MedicionesSilo");
                });

            modelBuilder.Entity("ECOCEMProyect.Empresa", b =>
                {
                    b.Navigation("Sedes");
                });

            modelBuilder.Entity("ECOCEMProyect.Herramientas", b =>
                {
                    b.Navigation("HerramientaMantNecesarios");

                    b.Navigation("OrdenTrabajoHerramientas");
                });

            modelBuilder.Entity("ECOCEMProyect.MantenimientoNecesario", b =>
                {
                    b.Navigation("HerramientaMantNecesarios");
                });

            modelBuilder.Entity("ECOCEMProyect.OrdenTrabajo", b =>
                {
                    b.Navigation("OrdenTrabajoHerramientas");

                    b.Navigation("OrdenTrabajoRoturaEquipo");

                    b.Navigation("OrdenesAMRealizadas");
                });

            modelBuilder.Entity("ECOCEMProyect.RoturaEquipo", b =>
                {
                    b.Navigation("OrdenTrabajoRoturaEquipo");
                });

            modelBuilder.Entity("ECOCEMProyect.Sede", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Trabajadores");
                });

            modelBuilder.Entity("ECOCEMProyect.TipoEquipo", b =>
                {
                    b.Navigation("Equipo");

                    b.Navigation("MantenimientosNecesarios");
                });

            modelBuilder.Entity("ECOCEMProyect.Trabajador", b =>
                {
                    b.Navigation("OrdenesTrabajoAtendidas");
                });

            modelBuilder.Entity("ECOCEMProyect.Venta", b =>
                {
                    b.Navigation("Cargas");
                });

            modelBuilder.Entity("ECOCEMProyect.MantenimientoPlanificado", b =>
                {
                    b.Navigation("MantenimientosNecesarios");
                });
#pragma warning restore 612, 618
        }
    }
}
